name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-deb
      run: sudo apt-get -y update && sudo apt-get -y install cargo
    - name: Build
      run: cargo build --release --verbose
    - name: Upload Deb Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rustscan
        path: ./target/release/rustscan
